# Generated by Django 4.1.7 on 2023-03-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('interests', models.TextField()),
                ('personality_traits', models.TextField()),
                ('education', models.CharField(max_length=100)),
                ('achievements', models.TextField()),
                ('personal_statement', models.TextField()),
            ],
        ),
    ]
